<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="JCB-MacBook-Pro.local" ignored="10" tests="6" failures="1" timestamp="30 Mar 2020 01:11:27 GMT" time="2.711" errors="0">
  <testcase name="searchOrderByID404" time="0.7" classname="Get404"/>
  <testcase name="deleteOrderNotFound" time="0.389" classname="DeleteAndPost"/>
  <testcase name="notFoundMessageIsCorrect" time="0.381" classname="BodyTest"/>
  <testcase name="deleteNotFoundMessageIsCorrect" time="0.472" classname="BodyTest">
    <skipped/>
  </testcase> <!-- deleteNotFoundMessageIsCorrect -->
  <testcase name="deleteNotFoundMessageIsCorrect" time="0.369" classname="BodyTest">
    <skipped/>
  </testcase> <!-- deleteNotFoundMessageIsCorrect -->
  <testcase name="deleteNotFoundMessageIsCorrect" time="0.379" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown]
at BodyTest.deleteNotFoundMessageIsCorrect(BodyTest.java:86)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- deleteNotFoundMessageIsCorrect -->
  <testcase name="createOrder200" time="0.0" classname="DeleteAndPost">
    <ignored/>
  </testcase> <!-- createOrder200 -->
  <testcase name="searchOrderByID400" time="0.0" classname="Get404">
    <ignored/>
  </testcase> <!-- searchOrderByID400 -->
  <testcase name="nonExistingUrlReturns404" time="0.0" classname="Get404">
    <ignored/>
  </testcase> <!-- nonExistingUrlReturns404 -->
  <testcase name="deleteInvalidIDSupplied" time="0.0" classname="DeleteAndPost">
    <ignored/>
  </testcase> <!-- deleteInvalidIDSupplied -->
  <testcase name="returnsCorrectOrderBodyResponse" time="0.0" classname="BodyTest">
    <ignored/>
  </testcase> <!-- returnsCorrectOrderBodyResponse -->
  <testcase name="invalidIDSuppliedMessageIsCorrect" time="0.0" classname="BodyTest">
    <ignored/>
  </testcase> <!-- invalidIDSuppliedMessageIsCorrect -->
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.0" classname="BodyTest">
    <ignored/>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="createInvalidOrder400" time="0.0" classname="DeleteAndPost">
    <ignored/>
  </testcase> <!-- createInvalidOrder400 -->
  <testcase name="createOrder500" time="0.0" classname="DeleteAndPost">
    <ignored/>
  </testcase> <!-- createOrder500 -->
  <testcase name="deleteIsSuccessful" time="0.0" classname="DeleteAndPost">
    <ignored/>
  </testcase> <!-- deleteIsSuccessful -->
</testsuite>
