<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="JCB-MacBook-Pro.local" name="BodyTest" tests="18" failures="12" timestamp="30 Mar 2020 01:12:09 GMT" time="8.270" errors="0">
  <testcase name="returnsCorrectOrderBodyResponse" time="0.580" classname="BodyTest"/>
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.450" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown],
	expected [Invalid ID supplied] but found [java.lang.NumberFormatException: For input string: &quot;3.5&quot;]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown],
expected [Invalid ID supplied] but found [java.lang.NumberFormatException: For input string: "3.5"]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at BodyTest.deleteInvalidIDMessageIsCorrect(BodyTest.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.384" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown],
	expected [Invalid ID supplied] but found [Order Not Found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown],
expected [Invalid ID supplied] but found [Order Not Found]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at BodyTest.deleteInvalidIDMessageIsCorrect(BodyTest.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.533" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown],
	expected [Invalid ID supplied] but found [Order Not Found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown],
expected [Invalid ID supplied] but found [Order Not Found]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at BodyTest.deleteInvalidIDMessageIsCorrect(BodyTest.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.411" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown],
	expected [Invalid ID supplied] but found [Order Not Found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown],
expected [Invalid ID supplied] but found [Order Not Found]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at BodyTest.deleteInvalidIDMessageIsCorrect(BodyTest.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="invalidIDSuppliedMessageIsCorrect" time="0.955" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Invalid ID supplied] but found [Order not found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Invalid ID supplied] but found [Order not found]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at BodyTest.invalidIDSuppliedMessageIsCorrect(BodyTest.java:71)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- invalidIDSuppliedMessageIsCorrect -->
  <testcase name="invalidIDSuppliedMessageIsCorrect" time="0.366" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Invalid ID supplied] but found [Order not found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Invalid ID supplied] but found [Order not found]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at BodyTest.invalidIDSuppliedMessageIsCorrect(BodyTest.java:71)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- invalidIDSuppliedMessageIsCorrect -->
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.449" classname="BodyTest">
    <skipped/>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.455" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown],
	expected [Invalid ID supplied] but found [Order Not Found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown],
expected [Invalid ID supplied] but found [Order Not Found]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at BodyTest.deleteInvalidIDMessageIsCorrect(BodyTest.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.356" classname="BodyTest">
    <skipped/>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="notFoundMessageIsCorrect" time="0.383" classname="BodyTest"/>
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.439" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown],
	expected [Invalid ID supplied] but found [java.lang.NumberFormatException: For input string: &quot;3.5&quot;]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown],
expected [Invalid ID supplied] but found [java.lang.NumberFormatException: For input string: "3.5"]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at BodyTest.deleteInvalidIDMessageIsCorrect(BodyTest.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="deleteNotFoundMessageIsCorrect" time="0.381" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at BodyTest.deleteNotFoundMessageIsCorrect(BodyTest.java:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- deleteNotFoundMessageIsCorrect -->
  <testcase name="invalidIDSuppliedMessageIsCorrect" time="0.497" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Invalid ID supplied] but found [Order not found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Invalid ID supplied] but found [Order not found]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at BodyTest.invalidIDSuppliedMessageIsCorrect(BodyTest.java:71)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- invalidIDSuppliedMessageIsCorrect -->
  <testcase name="deleteNotFoundMessageIsCorrect" time="0.473" classname="BodyTest">
    <skipped/>
  </testcase> <!-- deleteNotFoundMessageIsCorrect -->
  <testcase name="deleteInvalidIDMessageIsCorrect" time="0.407" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown],
	expected [Invalid ID supplied] but found [Order Not Found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown],
expected [Invalid ID supplied] but found [Order Not Found]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at BodyTest.deleteInvalidIDMessageIsCorrect(BodyTest.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- deleteInvalidIDMessageIsCorrect -->
  <testcase name="deleteNotFoundMessageIsCorrect" time="0.370" classname="BodyTest">
    <skipped/>
  </testcase> <!-- deleteNotFoundMessageIsCorrect -->
  <testcase name="invalidIDSuppliedMessageIsCorrect" time="0.381" classname="BodyTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [error] but found [unknown],
	expected [Invalid ID supplied] but found [java.lang.NumberFormatException: For input string: &quot;3.5&quot;]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [error] but found [unknown],
expected [Invalid ID supplied] but found [java.lang.NumberFormatException: For input string: "3.5"]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at BodyTest.invalidIDSuppliedMessageIsCorrect(BodyTest.java:71)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- invalidIDSuppliedMessageIsCorrect -->
</testsuite> <!-- BodyTest -->
